export let words5en = ['abbey', 'abuse', 'acorn', 'actor', 'admin', 'adobe', 'adult', 'afoul', 'agent', 'aglet',
    'agony', 'alarm', 'album', 'alder', 'alert', 'alias', 'alibi', 'alien', 'alley', 'alloy', 'alpha', 'altar',
    'amber', 'angel', 'anger', 'angle', 'anime', 'anise', 'ankle', 'apple', 'apron', 'arena', 'armor', 'array',
    'arrow', 'ascot', 'aside', 'aspic', 'asset', 'attic', 'audit', 'award', 'bacon', 'badge', 'bagel', 'baggy',
    'baker', 'banjo', 'barge', 'basil', 'basin', 'basis', 'bayou', 'beach', 'beard', 'beast', 'beech', 'being',
    'belly', 'bench', 'beret', 'berry', 'bidet', 'bijou', 'birch', 'birth', 'black', 'blade', 'blame', 'blank',
    'blast', 'blend', 'blind', 'block', 'blood', 'bloom', 'blush', 'board', 'bongo', 'bonus', 'boost', 'booty',
    'bosom', 'bough', 'bower', 'boxer', 'brace', 'brain', 'brake', 'brand', 'brass', 'bread', 'break', 'brick',
    'bride', 'brief', 'brink', 'broad', 'brood', 'brook', 'broom', 'brown', 'brush', 'buddy', 'buggy', 'bugle',
    'bunch', 'burro', 'burst', 'buyer', 'cabin', 'cable', 'cacao', 'caddy', 'cadet', 'camel', 'cameo', 'canal',
    'candy', 'canoe', 'canon', 'caper', 'capon', 'cargo', 'carol', 'carry', 'catch', 'cause', 'cello', 'chafe',
    'chain', 'chair', 'chalk', 'chaos', 'chard', 'charm', 'chart', 'chasm', 'check', 'cheek', 'cheer', 'chess',
    'chest', 'chick', 'chief', 'child', 'chili', 'chill', 'chime', 'chino', 'chive', 'choir', 'chops', 'chord',
    'chuck', 'churn', 'claim', 'clamp', 'clank', 'clasp', 'class', 'clave', 'cleat', 'cleft', 'clerk', 'click',
    'cliff', 'climb', 'cloak', 'clock', 'clogs', 'clone', 'close', 'cloth', 'cloud', 'clove', 'coach', 'coast',
    'cocoa', 'codon', 'colon', 'color', 'comic', 'comma', 'conga', 'congo', 'coral', 'corps', 'couch', 'cough',
    'count', 'court', 'cover', 'crack', 'craft', 'crane', 'crash', 'crate', 'crazy', 'cream', 'creek', 'crepe',
    'crest', 'crime', 'crisp', 'crook', 'cross', 'croup', 'crowd', 'crown', 'crude', 'crumb', 'crush', 'crust',
    'curio', 'curry', 'curse', 'curve', 'cycle', 'cynic', 'daddy', 'daily', 'dairy', 'daisy', 'dance', 'death',
    'delay', 'demon', 'demur', 'denim', 'depot', 'depth', 'derby', 'devil', 'diary', 'digit', 'diner', 'disco',
    'divan', 'diver', 'doing', 'dolor', 'donor', 'donut', 'doubt', 'dough', 'dozen', 'draft', 'drain', 'drake',
    'drama', 'dream', 'dress', 'drill', 'drink', 'drive', 'drunk', 'dryer', 'dwarf', 'dwell', 'eagle', 'earth',
    'easel', 'eaves', 'edger', 'elbow', 'elite', 'elver', 'email', 'emery', 'enemy', 'entry', 'epoch', 'epoxy',
    'equal', 'error', 'essay', 'ethyl', 'event', 'exile', 'eyrie', 'facet', 'fairy', 'faith', 'fanny', 'fault',
    'favor', 'feast', 'fence', 'ferry', 'fetus', 'fiber', 'fibre', 'field', 'fiery', 'fifth', 'fight', 'filly',
    'filth', 'final', 'finer', 'first', 'flair', 'flame', 'flare', 'flash', 'fleck', 'flesh', 'flick', 'flint',
    'flock', 'flood', 'floor', 'flour', 'fluke', 'flume', 'flung', 'flute', 'focus', 'foray', 'force', 'forte',
    'forum', 'frame', 'fraud', 'freak', 'freon', 'fries', 'frock', 'front', 'frost', 'frown', 'fruit', 'furry',
    'futon', 'gaffe', 'gator', 'gauge', 'gavel', 'genie', 'genre', 'ghost', 'giant', 'gland', 'glass', 'globe',
    'gloom', 'glory', 'glove', 'going', 'goose', 'grace', 'grade', 'graft', 'grain', 'grand', 'grant', 'grape',
    'graph', 'grasp', 'grass', 'gravy', 'greed', 'green', 'grief', 'grill', 'group', 'grove', 'guard', 'guava',
    'guess', 'guest', 'guide', 'guilt', 'habit', 'haste', 'haunt', 'haven', 'havoc', 'hazel', 'heart', 'heavy',
    'hedge', 'hello', 'herbs', 'heron', 'hobby', 'honey', 'honor', 'horde', 'horse', 'horst', 'hotel', 'hound',
    'house', 'hovel', 'human', 'humor', 'hurry', 'hutch', 'hyena', 'icing', 'ideal', 'idiom', 'idiot', 'igloo',
    'image', 'inbox', 'index', 'infix', 'inlay', 'input', 'irony', 'issue', 'ivory', 'jeans', 'jelly', 'jewel',
    'jiffy', 'joint', 'judge', 'juice', 'jumbo', 'kayak', 'kazoo', 'kebab', 'kendo', 'ketch', 'kiosk', 'kitty',
    'knife', 'knock', 'koala', 'label', 'labor', 'ladle', 'lanai', 'larch', 'larva', 'latex', 'lathe', 'latte',
    'laugh', 'layer', 'leash', 'leave', 'legal', 'lemon', 'lemur', 'level', 'lever', 'light', 'lilac', 'limit',
    'linen', 'liner', 'lipid', 'liver', 'llama', 'lobby', 'local', 'logic', 'login', 'louse', 'lover', 'lunch',
    'lunge', 'lycra', 'macaw', 'macro', 'madam', 'magic', 'maize', 'major', 'maker', 'mambo', 'mango', 'manor',
    'maple', 'march', 'marsh', 'match', 'maybe', 'mayor', 'means', 'mecca', 'medal', 'media', 'melon', 'merit',
    'messy', 'metal', 'meter', 'metro', 'might', 'minor', 'miter', 'mixer', 'mocha', 'mochi', 'model', 'modem',
    'molar', 'money', 'month', 'moody', 'moose', 'moron', 'motel', 'motor', 'mound', 'mouse', 'mouth', 'mover',
    'movie', 'mower', 'music', 'nasal', 'nerve', 'nexus', 'niche', 'niece', 'night', 'ninja', 'noise', 'north',
    'novel', 'nudge', 'nurse', 'nylon', 'nymph', 'oasis', 'ocean', 'octet', 'offer', 'oldie', 'olive', 'omega',
    'onion', 'onset', 'opera', 'opium', 'order', 'organ', 'other', 'otter', 'ounce', 'ovary', 'owner', 'ozone',
    'pagan', 'paint', 'panda', 'panel', 'panic', 'pansy', 'pants', 'panty', 'paper', 'parka', 'party', 'pasta',
    'paste', 'patch', 'patio', 'patty', 'pause', 'payee', 'peace', 'peach', 'pearl', 'pecan', 'pedal', 'pence',
    'penny', 'peony', 'perch', 'petal', 'phase', 'phone', 'photo', 'piano', 'piece', 'piety', 'pilaf', 'pilot',
    'pinot', 'pinto', 'pitch', 'pizza', 'place', 'plain', 'plane', 'plant', 'plate', 'pleat', 'plier', 'plume',
    'point', 'poker', 'polyp', 'poppy', 'porch', 'potty', 'pouch', 'pound', 'power', 'press', 'price', 'pride',
    'print', 'prior', 'prize', 'probe', 'proof', 'prose', 'prune', 'pulse', 'punch', 'pupil', 'puppy', 'purse',
    'quail', 'quart', 'queen', 'query', 'quest', 'quiet', 'quill', 'quilt', 'quota', 'quote', 'rabbi', 'racer',
    'radar', 'radio', 'rainy', 'raise', 'rally', 'ramen', 'ramie', 'ranch', 'range', 'ratio', 'raven', 'rayon',
    'razor', 'reach', 'realm', 'rebel', 'relay', 'reply', 'reset', 'rhyme', 'rider', 'ridge', 'rifle', 'right',
    'riser', 'river', 'roast', 'robin', 'robot', 'round', 'route', 'rugby', 'ruler', 'rumor', 'sabre', 'saint',
    'salad', 'salon', 'salsa', 'satin', 'sauce', 'scale', 'scalp', 'scarf', 'scene', 'scent', 'scope', 'score',
    'scorn', 'scout', 'scrap', 'screw', 'scrim', 'scrip', 'sense', 'sepal', 'serum', 'sewer', 'shack', 'shade',
    'shame', 'shape', 'share', 'shark', 'shawl', 'shear', 'sheep', 'sheet', 'shelf', 'shell', 'shift', 'shine',
    'shirt', 'shoat', 'shock', 'shoes', 'shoot', 'shore', 'short', 'shout', 'shred', 'siege', 'sight', 'silly',
    'sitar', 'skate', 'skean', 'skill', 'skirt', 'skull', 'skunk', 'slang', 'slash', 'slate', 'slave', 'sleep',
    'sleet', 'slice', 'slide', 'slime', 'slope', 'sloth', 'slump', 'smell', 'smile', 'smith', 'smock', 'smoke',
    'smolt', 'snack', 'snail', 'snake', 'snarl', 'snuck', 'socks', 'sonar', 'sound', 'south', 'space', 'spade',
    'spark', 'spasm', 'spawn', 'spear', 'speed', 'spell', 'spelt', 'spice', 'spike', 'spill', 'spine', 'spite',
    'split', 'spool', 'spoon', 'spork', 'sport', 'sprag', 'sprat', 'spray', 'spree', 'spume', 'squid', 'stack',
    'staff', 'stage', 'stain', 'stair', 'stake', 'stalk', 'stall', 'stamp', 'stand', 'start', 'state', 'steak',
    'steam', 'steel', 'stick', 'still', 'sting', 'stock', 'stole', 'stone', 'stool', 'store', 'storm', 'story',
    'stove', 'strap', 'straw', 'strip', 'study', 'stuff', 'stump', 'style', 'suede', 'sugar', 'suite', 'surge',
    'sushi', 'swamp', 'swath', 'sweat', 'swell', 'swine', 'swing', 'sword', 'synod', 'syrup', 'tabby', 'table',
    'taste', 'tempo', 'tenet', 'tenor', 'tenth', 'tepee', 'theft', 'theme', 'thief', 'thigh', 'thing', 'thong',
    'thorn', 'thumb', 'thump', 'thyme', 'tiara', 'tiger', 'timer', 'title', 'toast', 'today', 'tonic', 'tooth',
    'topic', 'toque', 'torso', 'torte', 'total', 'touch', 'towel', 'tower', 'trace', 'track', 'tract', 'trade',
    'trail', 'train', 'trait', 'tramp', 'trash', 'treat', 'trend', 'triad', 'trial', 'tribe', 'trick', 'troop',
    'trout', 'trove', 'truck', 'trunk', 'trust', 'truth', 'tuber', 'tulip', 'tummy', 'tunic', 'tweet', 'twine',
    'twins', 'twist', 'uncle', 'union', 'unity', 'upper', 'usage', 'usher', 'usual', 'value', 'vault', 'veldt',
    'venom', 'venti', 'venue', 'verse', 'verve', 'video', 'villa', 'vinyl', 'viola', 'virus', 'visit', 'visor',
    'vista', 'vitro', 'vixen', 'vodka', 'vogue', 'voice', 'vomit', 'voter', 'wafer', 'wagon', 'waist', 'waste',
    'watch', 'water', 'wedge', 'weird', 'whack', 'whale', 'wharf', 'wheat', 'wheel', 'whelp', 'white', 'whole',
    'whorl', 'widow', 'width', 'witch', 'woman', 'world', 'worry', 'worth', 'wound', 'wreck', 'wrist', 'wrong',
    'yacht', 'yahoo', 'yeast', 'young', 'youth', 'zebra'];

export let words4en = ['meat', 'year', 'data', 'food', 'bird', 'love', 'fact', 'idea', 'area', 'oven', 'week', 'exam',
    'army', 'goal', 'news', 'user', 'disk', 'road', 'role', 'soup', 'math', 'wood', 'unit', 'cell', 'lake', 'mood',
    'city', 'debt', 'loss', 'bath', 'mall', 'hair', 'mode', 'song', 'town', 'wife', 'gate', 'girl', 'hall', 'meal',
    'poem', 'desk', 'king', 'menu', 'beer', 'dirt', 'gene', 'lady', 'poet', 'tale', 'time', 'work', 'film', 'game',
    'life', 'form', 'part', 'fish', 'back', 'heat', 'hand', 'book', 'type', 'home', 'body', 'size', 'card', 'list',
    'mind', 'line', 'care', 'risk', 'word', 'name', 'boss', 'page', 'term', 'test', 'kind', 'soil', 'rate', 'site',
    'case', 'boat', 'cash', 'plan', 'side', 'rule', 'head', 'rock', 'salt', 'note', 'rent', 'bank', 'half', 'fire',
    'item', 'room', 'view', 'ball', 'gift', 'tool', 'wind', 'sign', 'task', 'hope', 'date', 'link', 'post', 'star',
    'self', 'shot', 'exit', 'lack', 'spot', 'wing', 'foot', 'rain', 'wall', 'base', 'pair', 'text', 'file', 'bowl',
    'club', 'edge', 'lock', 'pack', 'park', 'skin', 'sort', 'baby', 'dish', 'trip', 'gear', 'land',
    'sale', 'tree', 'wave', 'belt', 'copy', 'drop', 'path', 'step', 'face',
    'tour', 'blue', 'duty', 'hour', 'luck', 'milk', 'pipe', 'seat', 'team', 'crew', 'gold', 'mark', 'pain',
    'shop', 'suit', 'tone', 'band', 'bone', 'coat', 'door', 'east',
    'hole', 'hook', 'nose', 'rice', 'bill', 'cake', 'code', 'ease', 'farm', 'host', 'loan', 'nail', 'race', 'sand',
    'west', 'wine', 'blow', 'chip', 'dust', 'golf', 'iron', 'mail', 'mess', 'pool',
    'shoe', 'tank', 'bake', 'bell', 'bike', 'clue', 'diet', 'fear', 'fuel', 'pace', 'peak', 'till', 'yard', 'bend',
    'bite', 'harm', 'knee', 'load', 'neck', 'ruin', 'ship', 'snow', 'tune',
    'zone', 'boot', 'camp', 'hell', 'joke', 'jury', 'mate', 'ring', 'roof', 'rope', 'sail', 'sock',
    'will', 'many', 'most', 'make', 'good', 'look', 'help', 'read', 'keep', 'give', 'long', 'play', 'feel', 'high',
    'past', 'show', 'call', 'move', 'turn', 'hold', 'main', 'cook', 'cold', 'deal',
    'fall', 'talk', 'tell', 'cost', 'glad', 'rest', 'safe', 'stay', 'rise', 'walk', 'pick', 'lift', 'stop', 'gain',
    'rich', 'save', 'fail', 'lead', 'meet', 'sell', 'ride', 'wait', 'deep', 'flow',
    'dump', 'push', 'fill', 'jump', 'kick', 'pass', 'vast', 'beat', 'burn', 'dark', 'draw', 'hire', 'join',
    'kill', 'drag', 'pull', 'soft', 'wear', 'dead', 'feed', 'sing', 'wish', 'hang', 'hunt', 'hate', 'sick', 'hurt',
    'swim', 'wash', 'fold', 'grab', 'hide', 'miss', 'roll', 'sink', 'slip', 'calm', 'male', 'mine', 'rush',
    'bear', 'dare', 'dear', 'kiss', 'neat', 'quit', 'tear', 'wake', 'wrap'
];

export let words6en = ['people',
    'people', 'family', 'health', 'system', 'thanks', 'person', 'method', 'theory', 'nature', 'safety', 'player', 'policy',
    'series', 'camera', 'growth', 'income', 'energy', 'nation', 'moment', 'office', 'driver', 'flight',
    'length', 'dealer', 'member', 'advice', 'effort', 'wealth', 'county', 'estate', 'recipe', 'studio', 'agency', 'memory',
    'aspect', 'cancer', 'region', 'device', 'engine', 'height', 'sample', 'cousin', 'editor', 'extent', 'guitar', 'leader',
    'singer', 'tennis', 'basket', 'church', 'coffee', 'dinner', 'orange', 'poetry', 'police', 'sector', 'volume', 'farmer',
    'injury', 'speech', 'winner', 'worker', 'writer', 'breath', 'cookie', 'drawer', 'insect', 'ladder', 'potato', 'sister',
    'tongue', 'affair', 'client', 'throat', 'number', 'market', 'course', 'school', 'amount', 'answer', 'matter', 'access',
    'garden', 'reason', 'future', 'demand', 'action', 'record', 'result', 'period', 'chance', 'figure', 'source', 'design',
    'object', 'profit', 'inside', 'stress', 'review', 'screen', 'medium', 'bottom', 'choice', 'impact', 'career', 'credit',
    'square', 'effect', 'friend', 'couple', 'debate', 'living', 'summer', 'button', 'desire', 'notice', 'damage', 'target',
    'animal', 'author', 'budget', 'ground', 'lesson', 'minute', 'bridge', 'letter', 'option', 'plenty', 'weight', 'factor',
    'master', 'muscle', 'appeal', 'mother', 'season', 'signal', 'spirit', 'street', 'status', 'ticket', 'degree', 'doctor',
    'father', 'stable', 'detail', 'shower', 'window', 'corner', 'finger', 'garage', 'manner', 'winter', 'battle', 'bother',
    'horror', 'phrase', 'relief', 'string', 'border', 'branch', 'breast', 'expert', 'league', 'native', 'parent', 'salary',
    'silver', 'tackle', 'assist', 'closet', 'collar', 'jacket', 'reward', 'bottle', 'candle', 'flower', 'lawyer', 'mirror',
    'purple', 'stroke', 'switch', 'bitter', 'carpet', 'island', 'priest', 'resort', 'scheme', 'script', 'public', 'common',
    'change', 'simple', 'second', 'single', 'travel', 'excuse', 'search', 'remove', 'return', 'middle', 'charge', 'active',
    'visual', 'affect', 'report', 'beyond', 'junior', 'unique', 'listen', 'handle', 'finish', 'normal', 'secret', 'spread',
    'spring', 'cancel', 'formal', 'remote', 'double', 'attack', 'wonder', 'annual', 'nobody', 'repeat', 'divide', 'survey',
    'escape', 'gather', 'repair', 'strike', 'employ', 'mobile', 'senior', 'strain', 'yellow', 'permit', 'abroad', 'prompt',
    'refuse', 'regret', 'reveal', 'female', 'invite', 'resist', 'stupid'];

export let words7en = ['history', 'reading', 'problem', 'control', 'ability', 'science', 'library', 'product',
    'society', 'quality', 'variety', 'country', 'physics', 'thought', 'freedom', 'writing',
    'article', 'fishing', 'failure', 'meaning', 'teacher', 'disease', 'success', 'student',
    'context', 'finding', 'message', 'concept', 'housing', 'opinion', 'payment', 'reality',
    'passion', 'setting', 'college', 'storage', 'version', 'alcohol', 'highway', 'mixture',
    'tension', 'anxiety', 'climate', 'emotion', 'manager', 'charity', 'outcome', 'revenue',
    'session', 'cabinet', 'clothes', 'drawing', 'hearing', 'vehicle', 'airport', 'arrival',
    'chapter', 'village', 'warning', 'courage', 'garbage', 'grocery', 'penalty', 'wedding',
    'analyst', 'bedroom', 'diamond', 'fortune', 'funeral', 'speaker', 'surgery', 'trainer',
    'example', 'process', 'economy', 'company', 'service', 'picture', 'section', 'nothing',
    'subject', 'weather', 'program', 'chicken', 'feature', 'purpose', 'outside', 'benefit',
    'account', 'balance', 'machine', 'address', 'average', 'culture', 'morning', 'contact',
    'network', 'attempt', 'capital', 'plastic', 'feeling', 'savings', 'officer', 'trouble',
    'maximum', 'quarter', 'traffic', 'kitchen', 'minimum', 'project', 'finance', 'mission',
    'contest', 'lecture', 'meeting', 'parking', 'partner', 'profile', 'respect', 'routine',
    'airline', 'evening', 'holiday', 'husband', 'mistake', 'package', 'patient', 'stomach',
    'tourist', 'brother', 'opening', 'pattern', 'request', 'shelter', 'comment', 'monitor',
    'weekend', 'welcome', 'bicycle', 'concert', 'counter', 'leather', 'pension', 'channel',
    'comfort', 'passage', 'promise', 'station', 'witness', 'general', 'tonight', 'current',
    'natural', 'special', 'working', 'primary', 'produce', 'present', 'support', 'complex',
    'regular', 'reserve', 'classic', 'private', 'western', 'concern', 'leading', 'release',
    'display', 'extreme', 'deposit', 'advance', 'consist', 'forever', 'impress', 'whereas',
    'combine', 'command', 'initial', 'mention', 'scratch', 'illegal', 'respond', 'convert',
    'recover', 'resolve', 'suspect', 'anybody', 'stretch'];

export let words8en = ['computer', 'software', 'internet', 'activity', 'industry', 'language', 'security', 'analysis',
    'strategy', 'instance', 'audience', 'marriage', 'medicine', 'location', 'addition', 'painting',
    'politics', 'decision', 'property', 'shopping', 'category', 'magazine', 'teaching', 'customer',
    'resource', 'patience', 'solution', 'attitude', 'director', 'response', 'argument', 'contract',
    'emphasis', 'currency', 'republic', 'delivery', 'election', 'football', 'guidance', 'priority',
    'elevator', 'employee', 'employer', 'disaster', 'feedback', 'homework', 'judgment', 'relation',
    'accident', 'baseball', 'database', 'hospital', 'presence', 'proposal', 'quantity', 'reaction',
    'weakness', 'ambition', 'bathroom', 'birthday', 'midnight', 'platform', 'stranger', 'sympathy',
    'business', 'interest', 'training', 'practice', 'research', 'exercise', 'building', 'material',
    'question', 'standard', 'exchange', 'position', 'pressure', 'function', 'distance', 'discount',
    'register', 'campaign', 'evidence', 'strength', 'relative', 'progress', 'daughter', 'pleasure',
    'calendar', 'district', 'schedule', 'swimming', 'designer', 'mountain', 'occasion', 'sentence',
    'shoulder', 'vacation', 'document', 'mortgage', 'sandwich', 'surprise', 'champion', 'engineer',
    'entrance', 'incident', 'resident', 'specific', 'possible', 'personal', 'national', 'physical',
    'increase', 'purchase', 'positive', 'creative', 'original', 'negative', 'anything', 'familiar',
    'official', 'valuable', 'chemical', 'conflict', 'opposite', 'anywhere', 'internal', 'constant',
    'external', 'ordinary', 'struggle', 'upstairs', 'estimate', 'surround', 'tomorrow'];

export let colorList = ['#f66200', '#44cb02', '#0056f1', '#FFBB00'
    , '#ee00ee', '#aaaaaa', '#ff000f', '#00eaff',
    '#000000'];

export let colorListNames = ['orange', 'green', 'blue', 'yellow'
    , 'pink', 'gray', 'red', 'turquoise', 'black'];

export let termsEn = [
    {
        categoryName: 'Colors',
        words: ['Yellow', 'Blue', 'Black', 'White', 'Red', 'Grey', 'Green', 'Purple', 'Brown', 'Pink']
    },
    {
        categoryName: 'Numbers',
        words: ['Six', 'Four', 'Three', 'Two', 'One', 'Seven', 'Five', 'Eight', 'Nine', 'Ten']
    },
    {
        categoryName: 'Names',
        words: ['Walter', 'John', 'Sam', 'Tim', 'Michael', 'Bruno', 'Julia', 'Kevin', 'Anna', 'Pete', 'Jason', 'Julius',
            'Robert']
    },
    {
        categoryName: 'Cities',
        words: ['London', 'New York', 'Paris', 'Hamburg', 'Miami', 'Boston', 'Montreal', 'Rome', 'Sydney', 'Madrid',
            'Kape Town', 'Huston', 'Tokio', 'Kioto', 'Berlin', 'Hamburg', 'Frankfurt', 'Stuttgart', 'Amsterdam', 'Helsinki',
            'Toronto', 'Las Vegas', 'Lima']
    },
    {
        categoryName: 'Countries',
        words: ['USA', 'France', 'Germany', 'Spain', 'Japan', 'Italy', 'Ireland', 'Sweden', 'Canada', 'Australia', 'China',
            'Peru', 'Poland', 'Norway', 'Iceland', 'India', 'Kenia', 'Egypt', 'Israel', 'Oman', 'Irak', 'Iran', 'Greece']
    },
    {
        categoryName: 'Sports',
        words: ['Volleyball', 'Triathlon', 'Badminton', 'Baseball', 'Basketball',
            'Biathlon', 'Cricket', 'Curling', 'Golf', 'Handball', 'Hockey', 'Judo', 'Karate', 'Taekwondo', 'Tennis']
    },
    {
        categoryName: 'Animals',
        words: ['Monkey', 'Antelope', 'Beaver', 'Bee', 'Buzzard', 'Lizard', 'Polar bear', 'Elephant', 'Duck', 'Donkey',
            'Flamingo', 'Ferret', 'Vulture', 'Giraffe', 'Gorilla', 'Cock', 'Shark', 'Kangaroo', 'Rabbit', 'Crocodile',
            'Lion']
    },
    {
        categoryName: 'Fruits or Vegetables',
        words: ['Pineapple', 'Apple', 'Orange', 'Apricot', 'Avocado', 'Banana', 'Pear', 'Blackberry', 'Strawberry',
            'Peanut', 'Pomegranate', 'Raspberry', 'Cherry', 'Kiwi', 'Coconut', 'Mango', 'Melon', 'Grapefruit',
            'Peach', 'Plum', 'Gooseberry', 'Tomato', 'Walnut', 'Grape', 'Lemon']
    }
];

export let termsDe = [

    {
        categoryName: 'Farben',
        words: ['Beige', 'Blassgrün', 'Blau', 'Braun', 'Bunt', 'Cyan', 'Dunkelblau', 'Dunkelgrün',
            'Dunkeltürkis', 'Gelb', 'Gelbbraun', 'Gelbgrün', 'Goldfarben', 'Grau', 'Grün',
            'Grüngelb', 'Hellblau', 'Hellgrau', 'Hellgrün', 'Hellrosa', 'Himmelblau', 'Indigo',
            'Königsblau', 'Korallenrot', 'Lachsfarben', 'Lila', 'Limonengrün', 'Magenta',
            'Mandelweiß', 'Olivgrün', 'Pink', 'Rasengrün', 'Rosa', 'Rot', 'Schiefergrau', 'Schneeweiß',
            'Schwarz', 'Seegrün', 'Stahlblau', 'Türkis', 'Violett', 'Weiß']
    },
    {
        categoryName: 'Zahlen',
        words: ['Eins', 'Zwei', 'Drei', 'Vier', 'Fünf', 'Sechs', 'Sieben', 'Acht', 'Neun', 'Zen', 'Elf', 'Zwölf',
            'Dreizehn', 'Vierzehn', 'Zwanzig', 'Hundert', 'Tausend', 'Fünfzehn', 'Sechszehn', 'Null', 'Neunzig', 'Achtzig',
            'Fünfzig', 'Vierundzwanzig']
    },
    {
        categoryName: 'Namen',
        words: ['Walter', 'John', 'Tom', 'Tim', 'Michael', 'Bruno', 'Julia', 'Kevin', 'Anna', 'Stefan', 'Paul',
            'Alexander', 'Ben', 'Bernd', 'Jens', 'Heiko', 'Heinrich', 'Karl', 'Otto', 'Ottmar', 'Peter', 'Heinz',
            'Ulrich', 'Jan', 'Dirk', 'Erich']
    },
    {
        categoryName: 'Städte',
        words: ['London', 'New York', 'Paris', 'Hamburg', 'Miami', 'Boston', 'Montreal', 'Rom', 'Sydney', 'Berlin',
            'Frankfurt', 'Köln', 'Neapel', 'Tokio', 'Brisbane', 'Perth', 'Huston', 'Toronto', 'Dublin', 'Moskau',
            'Helsinki', 'Amsterdam', 'Dresden', 'Stuttgart', 'Zürich', 'Nürnberg', 'Stockholm', 'Mailand', 'Madrid']
    },
    {
        categoryName: 'Länder',
        words: ['USA', 'Frankreich', 'Deutschland', 'Spanien', 'Japan', 'Italien', 'Ireland', 'Schweden', 'Kanada',
            'Australien', 'Schweiz', 'Österreich', 'Dänemark', 'Polen', 'Litauen', 'Portugal', 'Mexiko', 'Kuba',
            'China', 'Tailand', 'Oman', 'Irak', 'Iran', 'Indien', 'Kenia', 'Ägypten', 'Namibia', 'Griechenland',
            'Türkei', 'Chile', 'Peru', 'Argentinien', 'Luxemburg', 'Israel', 'Neuseeland']
    }
    ,
    {
        categoryName: 'Sportarten',
        words: ['Ausdauerlauf', 'Bergsteigen', 'Bogenschießen', 'Eiskunstlauf', 'Eisschnellauf', 'Fechten', 'Fußball',
            'Gewichtheben', 'Joggen', 'Kugelstoßen', 'Leichtathletik', 'Ringen', 'Speerwerfen', 'Stabhochsprung',
            'Tischtennis', 'Volleyball', 'Triathlon', 'American Football', 'Badminton', 'Baseball', 'Basketball',
            'Beach Volleyball', 'Biathlon', 'Cricket', 'Curling', 'Golf', 'Handball', 'Hockey', 'Judo', 'Karate',
            'Taekwondo', 'Tennis']
    },
    {
        categoryName: 'Tierarten',
        words: ['Affe', 'Antilope', 'Biber', 'Biene', 'Bussard', 'Eidechse', 'Eisbär', 'Elefant', 'Ente', 'Esel',
            'Flamingo', 'Frettchen', 'Geier', 'Giraffe', 'Gorilla', 'Hahn', 'Hai', 'Känguru', 'Kaninchen',
            'Krokodil', 'Löwe', 'Hund', 'Katze', 'Maus', 'Hase', 'Ree', 'Aal', 'Adler', 'Alligator', 'Ameise',
            'Amsel', 'Bär', 'Büffel', 'Chamäleon', 'Dachs', 'Delfin', 'Dromedar', 'Eichhörnchen', 'Elch', 'Erdmännchen',
            'Eule', 'Fasan', 'Faultier', 'Fisch', 'Fledermaus', 'Fliege', 'Flughund', 'Frosch', 'Fuchs', 'Gans',
            'Gecko', 'Gepard', 'Hamster', 'Heuschrecke', 'Hirsch', 'Hornisse', 'Huhn', 'Hummel', 'Hummer', 'Igel',
            'Iltis', 'Jaguar', 'Kakadu', 'Kamel', 'Känguru', 'Kaninchen', 'Karpfen', 'Krake', 'Krebs', 'Kuckuck',
            'Kuh', 'Lama', 'Leopard', 'Libelle', 'Marder', 'Maulwurf', 'Mücke', 'Mungo', 'Murmeltier', 'Nashorn',
            'Nilpferd', 'Orang-Utan', 'Orca', 'Panda', 'Papagei', 'Pavian', 'Pfau', 'Pferd', 'Pinguin', 'Piranha',
            'Pony', 'Qualle', 'Ratte', 'Regenwurm', 'Robbe', 'Schaf', 'Schildkröte', 'Schimpanse', 'Schlange',
            'Schmetterling', 'Schnecke', 'Schwein', 'Seelöwe', 'Seepferdchen', 'Skorpion', 'Spinne', 'Storch', 'Strauß',
            'Taube', 'Tiger', 'Tintenfisch', 'Wal', 'Walross', 'Waschbär', 'Wespe', 'Wildschwein', 'Wolf', 'Zebra']
    },
    {
        categoryName: 'Obst und Gemüse',
        words: ['Ananas', 'Apfel', 'Apfelsine', 'Aprikose', 'Avocado', 'Banane', 'Birne', 'Brombeere', 'Erdbeere',
            'Erdnuss', 'Granatapfel', 'Himbeere', 'Kirsche', 'Kiwi', 'Kokusnuss', 'Mango', 'Melone', 'Grapefruit',
            'Pfirsich', 'Pflaume', 'Stachelbeere', 'Tomate', 'Walnuss', 'Weintraube', 'Zitrone']
    }
];


export let words4de = ['Güte',
    'Jahr', 'Zeit', 'Euro', 'Frau', 'Kind', 'Land', 'Mann', 'Ende',
    'Herr', 'Haus', 'Teil', 'Fall', 'Bild', 'Welt', 'Name', 'Juni',
    'März', 'Geld', 'Wort', 'Mark', 'Ziel', 'Juli', 'Film', 'Gast',
    'Zahl', 'Werk', 'Team', 'Buch', 'Foto', 'Hand', 'Band', 'Sieg',
    'Bank', 'Wahl', 'Raum', 'Auto', 'Form', 'Sohn', 'Dame', 'Höhe',
    'Sinn', 'Auge', 'Lage', 'Idee', 'Satz', 'Text', 'Kopf', 'Wert',
    'Plan', 'Tier', 'Bund', 'Ding', 'Dorf', 'Arzt', 'Rede', 'Gott',
    'Herz', 'Chef', 'Volk', 'Bahn', 'Rang', 'Kurs', 'Info', 'Nähe',
    'Lied', 'Lauf', 'Sitz', 'Wald', 'Gruß', 'Ball', 'Luft', 'Spaß',
    'Baum', 'Liga', 'Berg', 'Grad', 'Dank', 'Feld', 'Club', 'Spur',
    'Chor', 'Burg', 'Hund', 'Erde', 'Tour', 'Fest', 'Rest', 'Post',
    'Star', 'Park', 'Rand', 'Stil', 'Kino', 'Ruhe', 'Wein', 'Büro',
    'Gang', 'Fluß', 'Gold', 'Tote', 'Dach', 'Bein', 'Netz', 'Wand',
    'Paar', 'Wind', 'Saal', 'Song', 'Ware', 'Meer', 'Holz', 'Mord',
    'Klub', 'West', 'Oper', 'Tanz', 'Ecke', 'Kauf', 'Haar', 'Haft',
    'Ring', 'Lust', 'Ehre', 'Show', 'Rock', 'Weiß', 'Turm', 'Test',
    'Bett', 'Jazz', 'Boot', 'Blut', 'Lohn', 'Nord', 'Held', 'Mühe',
    'Glas', 'Bier', 'Last', 'Türe', 'Flug', 'Bord', 'Nase', 'Cent',
    'Loch', 'Grab', 'Bach', 'Mund', 'Erbe', 'Jury', 'Note', 'Kern',
    'Zins', 'Löwe', 'Golf', 'Baby', 'Akte', 'Heim', 'Sand', 'Plus',
    'Trio', 'Haut', 'Ufer', 'Graf', 'Fund', 'Heft', 'Brot',
    'Witz', 'Wehr', 'Mond', 'Mode', 'Zahn', 'Kilo', 'Wohl', 'Fach',
    'Zelt', 'Nerv', 'Hall', 'Jagd', 'Hals', 'Dieb', 'Leib', 'Lady',
    'Lese', 'Müll', 'Zone', 'Hose', 'Heer', 'Blau', 'Lärm', 'Wild',
    'Lake', 'Hang', 'Böse', 'Etat', 'Pech', 'Horn', 'Norm', 'Wirt',
    'Laie', 'Salz', 'Halt', 'Beat', 'Helm', 'Maus', 'Krem', 'Rose',
    'Moor', 'Foul', 'Gelb', 'Sack', 'Reiz', 'Leid', 'Mama', 'Weib',
    'File', 'Flut', 'Exil', 'Stau', 'Lord', 'Lüge', 'Papa', 'Narr',
    'Girl', 'Zaun', 'Zeug', 'Bube', 'Sage', 'Topf', 'Fünf', 'Damm',
    'Taxi', 'Atem', 'Span', 'Lupe', 'Hase', 'Echo', 'Fort', 'Gras',
    'Huhn', 'Funk', 'Vogt', 'Obst', 'Rohr', 'Kohl', 'Fett', 'Fakt',
    'Aula', 'Käse', 'Adel', 'Vers', 'Camp', 'Flur', 'Solo', 'Takt',
    'Ruhm', 'Korb', 'Heil', 'Rind', 'Wolf', 'Wurf', 'Zoll', 'City',
    'Mars', 'Hemd', 'Opus', 'Hexe', 'Zorn', 'Tuch', 'Gift', 'Boom',
    'Code', 'Bann', 'Soul', 'Part', 'Kerl', 'Stab', 'Nest', 'Disk',
    'Acht', 'Demo', 'Reis', 'Korn', 'Duft', 'Fell', 'Chip',
    'Pfad', 'Urne', 'Port', 'Ofen', 'Hoch', 'Tank', 'Heck', 'Seil',
    'Asyl', 'Gabe', 'Punk', 'Pilz', 'Mine', 'List', 'Crew', 'Gute',
    'Lama', 'Bond', 'Affe', 'Pate', 'Bart', 'Übel', 'Harz', 'Dorn',
    'Klee', 'Pose', 'Neid', 'Ente', 'Matt', 'Tabu', 'Tief', 'Expo',
    'Gala', 'Sofa', 'Raub', 'Qual', 'Sekt', 'Keim', 'Pakt', 'Rate',
    'Reim', 'Mais', 'Wurm', 'Eins', 'Fels', 'Pool', 'Saft',
    'Mehl', 'Talk', 'Sarg', 'Hort', 'Gans', 'Koch', 'Mast', 'Moos',
    'Putz', 'Menü', 'Hehl', 'Arie', 'Eile', 'Watt', 'Hahn', 'Steg',
    'Giro', 'Idol', 'Fuge', 'Elan', 'Vita', 'Mini', 'Atom', 'Veto',
    'Mist', 'Back', 'Most', 'Drei', 'Hirn', 'Diät', 'Puls', 'Grau',
    'Herd', 'Polo', 'Esel', 'Grün', 'Harm', 'Folk', 'Tüte', 'Food',
    'Enge', 'Kult', 'Lift', 'Kalb', 'Pest', 'Clan', 'Arge', 'Ulme',
    'Uran', 'Kick', 'Kost', 'Maul', 'Page', 'Oase', 'Kran', 'Koma',
    'Fang', 'Judo', 'Vieh', 'Cash', 'Eule', 'Flop', 'Bude',
    'Hohn', 'Lamm', 'Yoga', 'Gier', 'Woge', 'Trip', 'Ahne', 'Made',
    'Gage', 'Bote', 'Deck', 'Poet', 'Hopp', 'Kamm', 'Muse', 'Reue',
    'Aura', 'Pult', 'Loge', 'Lack', 'Ader', 'Base', 'Blei',
    'Verb', 'Ruin', 'Biss', 'Rast', 'Igel', 'Pony', 'Wade', 'Vier',
    'Puck', 'Oboe', 'Eden', 'Teig', 'Pelz', 'Dual', 'Lehm', 'Naht',
    'Spot', 'Rebe', 'Bike', 'Knie', 'Tram', 'Walz', 'Wehe', 'Vase',
    'Dino', 'Hast', 'Akku', 'Ruck', 'Kanu', 'Yard', 'Trab', 'Wahn',
    'Keks', 'Dose', 'Zehe', 'Farm', 'Senf'];

export let words5de = ['Stadt',
    'Woche', 'Frage', 'Seite', 'Platz', 'Leben', 'Spiel', 'Thema', 'Grund',
    'Punkt', 'Monat', 'April', 'Meter', 'Staat', 'Leute', 'Preis', 'Folge',
    'Kreis', 'Musik', 'Firma', 'Recht', 'Titel', 'Autor', 'Vater', 'Sache',
    'Rolle', 'Abend', 'Stück', 'Blick', 'Hilfe', 'Markt', 'Mitte', 'Kunst',
    'Krieg', 'Nacht', 'Kraft', 'Kampf', 'Liste', 'Opfer', 'Kunde', 'Reihe',
    'Karte', 'Runde', 'Weise', 'Bühne', 'Alter', 'Druck', 'Stand', 'Linie',
    'Union', 'Liebe', 'Roman', 'Angst', 'Sicht', 'Start', 'Boden', 'Sport',
    'Datum', 'Glück', 'Regel', 'Insel', 'Licht', 'Hotel', 'Täter', 'Menge',
    'Junge', 'Osten', 'Natur', 'Weste', 'Motto', 'Serie', 'Datei', 'Anlaß',
    'Pause', 'Macht', 'Brief', 'Tisch', 'Album', 'Szene', 'Halle', 'Farbe',
    'Beruf', 'Krise', 'Sorge', 'Suche', 'Leser', 'Figur', 'Armee', 'Wagen',
    'Süden', 'Fahrt', 'Sonne', 'Regie', 'Basis', 'Aktie', 'Galle', 'Größe',
    'Linke', 'Tonne', 'Zweck', 'Traum', 'Feuer', 'König', 'Wille', 'Waffe',
    'Geist', 'Gerät', 'Blatt', 'Senat', 'Kreuz', 'Bezug', 'Stern', 'Ebene',
    'Vogel', 'Börse', 'Strom', 'Zeuge', 'Maler', 'Papst', 'Kasse', 'Messe',
    'Motor', 'Stein', 'Lager', 'Pferd', 'Marke', 'Summe', 'Zitat', 'Trend',
    'Beleg', 'Bauer', 'Phase', 'Liter', 'Klage', 'Schuß', 'Lehre',
    'Reich', 'Feier', 'Motiv', 'Seele', 'Radio', 'Zuruf', 'Länge', 'Ganze',
    'Coach', 'Stoff', 'Küche', 'Falle', 'Forum', 'Dauer', 'Laden', 'Mauer',
    'Regen', 'Umbau', 'Beste', 'Tempo', 'Hafen', 'Villa', 'Reise', 'Video',
    'Klima', 'Party', 'Wende', 'Profi', 'Front', 'Duell', 'Fisch', 'Masse',
    'Brand', 'Kader', 'Sturm', 'Probe', 'Erlös', 'Schuh', 'Krone', 'Griff',
    'Blume', 'Index', 'Stufe', 'Umzug', 'Rente', 'Stock', 'Welle', 'Image',
    'Klang', 'Wiese', 'Orgel', 'Schau', 'Konto', 'These', 'Droge', 'Küste',
    'Tiefe', 'Fürst', 'Pilot', 'Feind', 'Sturz', 'Übung', 'Wesen', 'Stamm',
    'Ärger', 'Abbau', 'Lücke', 'Kanal', 'Arena', 'Katze', 'Kürze', 'Islam',
    'Jäger', 'Zelle', 'Fonds', 'Fazit', 'Bruch', 'Brust', 'Wolke', 'Zeile',
    'Drama', 'Stuhl', 'Orden', 'Armut', 'Block', 'Derby', 'Blüte', 'Match',
    'Humor', 'Türke', 'Areal', 'Jungs', 'Chaos', 'Hürde', 'Mühle', 'Stolz',
    'Gunst', 'Bombe', 'Gramm', 'Quote', 'Tafel', 'Lokal', 'Pokal', 'Träne',
    'Kleid', 'Pfund', 'Blues', 'Fahne', 'Route', 'Hütte', 'Frist', 'Decke',
    'Miete', 'Tiger', 'Kugel', 'Hobby', 'Bitte', 'Milch', 'Minus', 'Bogen',
    'Anruf', 'Bibel', 'Paket', 'Laune', 'Enkel', 'Abzug', 'Onkel', 'Säule',
    'Gleis', 'Rasen', 'Organ', 'Lache', 'Sorte', 'Kurve', 'Moral', 'Stift',
    'Hitze', 'Kette', 'Faden', 'Bande', 'Story', 'Beute', 'Streß', 'Stich',
    'Anbau', 'Lippe', 'Trick', 'Feder', 'Tenor', 'Geste', 'Super', 'Label',
    'Wärme', 'Kälte', 'Schaf', 'Bauch', 'Stahl', 'Hügel', 'Virus', 'Queen',
    'Weite', 'Debüt', 'Remis', 'Prinz', 'Glanz', 'Ruine', 'Logik', 'Möbel',
    'Witwe', 'Votum', 'Münze', 'First', 'Fokus', 'Apfel', 'Nebel', 'Major',
    'Kopie', 'Labor', 'Gebot', 'Mönch', 'Genre', 'Würde', 'Elite', 'Wüste',
    'Abriß', 'Foyer', 'Model', 'Knabe', 'Fülle', 'Stall', 'Trost', 'Piste',
    'Wette', 'Maske', 'Rasse', 'Buche', 'Zweig', 'Kabel', 'Pirat', 'Brett',
    'Weile', 'Tante', 'Tarif', 'Funke', 'Unmut', 'Hölle', 'Treff', 'Ferne',
    'Garde', 'Indiz', 'Panik', 'Altar', 'Gasse', 'Leder', 'Staub', 'Zwang',
    'Kurde', 'Pater', 'Ernte', 'Baron', 'Hamas', 'Segen', 'Gebet', 'Kerze',
    'Grube', 'Höhle', 'Jubel', 'Ampel', 'Etage', 'Anzug', 'Freie', 'Wunde',
    'Rache', 'Essay', 'Treue', 'Kraut', 'Achse', 'Warte', 'Ozean', 'Photo',
    'Heide', 'Panne', 'Flora', 'Kiste', 'Taufe', 'Allee', 'Agent', 'Alarm',
    'Engel', 'Zunge', 'Regal', 'Ideal', 'Krimi', 'Teich', 'Eisen', 'Puppe',
    'Bauen', 'Härte', 'Gemüt', 'Hauch', 'Riese', 'Latte', 'Fleck', 'Handy',
    'Gehör', 'Draht', 'Stirn', 'Elend', 'Notiz', 'Sitte', 'Comic', 'Umweg',
    'Chart', 'Lampe', 'Beton', 'Frust', 'Jacke', 'Werft', 'Forst', 'Eiche',
    'Salon', 'Wurst', 'Meile', 'Luxus', 'Glied', 'Revue', 'Weide', 'Schar',
    'Lyrik', 'Ruder', 'Disco', 'Braut', 'Blitz', 'Pfeil', 'Nagel',
    'Bucht', 'Gnade', 'Biene', 'Suppe', 'Taube', 'Dosis', 'Asche', 'Segel',
    'Hörer', 'Clown', 'Neffe', 'Fähre', 'Ethik', 'Acker', 'Flöte', 'Porto',
    'Event', 'Kreml', 'Waage', 'Tritt', 'Wache', 'Salat', 'Trage', 'Sünde',
    'Bonus', 'Weber', 'Venus', 'Kripo', 'Magen', 'Guide', 'Leere', 'Boxer'];

export let words6de = ['Mensch',
    'Arbeit', 'Minute', 'Verein', 'Straße', 'Schule', 'Kirche', 'Januar', 'Gruppe',
    'Stunde', 'Partei', 'Erfolg', 'Person', 'August', 'Region', 'Montag', 'Anfang',
    'Chance', 'Stelle', 'Saison', 'Angabe', 'Eltern', 'Bürger', 'Mutter', 'Beginn',
    'Quelle', 'Rahmen', 'Stimme', 'Kritik', 'Antrag', 'Kosten', 'Wasser', 'Gesetz',
    'Klasse', 'Museum', 'Freund', 'Grenze', 'Gebiet', 'Verlag', 'Dollar', 'Lösung',
    'Kultur', 'Sommer', 'Hälfte', 'System', 'Mittel', 'Aktion', 'Partie', 'Gegner',
    'Schloß', 'Leiter', 'Medium', 'Gefahr', 'Besuch', 'Dienst', 'Kanton', 'Soldat',
    'Lehrer', 'Prozeß', 'Bruder', 'Anteil', 'Herbst', 'Fehler', 'Anlage', 'Wunsch',
    'Urteil', 'Bezirk', 'Schluß', 'Moment', 'Modell', 'Streit', 'Jugend', 'Nummer',
    'Rennen', 'Gefühl', 'Unfall', 'Winter', 'Gewinn', 'Spitze', 'Freude', 'Gewalt',
    'Umsatz', 'Termin', 'Schiff', 'Heimat', 'Schutz', 'Wissen', 'Finale', 'Wetter',
    'Reform', 'Inhalt', 'Norden', 'Truppe', 'Fläche', 'Fahrer', 'Studie', 'Morgen',
    'Körper', 'Risiko', 'Steuer', 'Schuld', 'Papier', 'Detail', 'Garten', 'Nation',
    'Archiv', 'Ausbau', 'Sänger', 'Brücke', 'Sieger', 'Weiter', 'Himmel', 'Praxis',
    'Handel', 'Umgang', 'Bilanz', 'Beweis', 'Spende', 'Anzahl', 'Anwalt', 'Senior',
    'Helfer', 'Objekt', 'Niveau', 'Aufbau', 'Presse', 'Absatz', 'Neubau', 'Umwelt',
    'Aspekt', 'Zugang', 'Glaube', 'Alltag', 'Wunder', 'Wähler', 'Kamera', 'Zimmer',
    'Besitz', 'Keller', 'Klinik', 'Stärke', 'Rücken', 'Träger', 'Strafe', 'Ansatz',
    'Bedarf', 'Mangel', 'Signal', 'Sender', 'Schlag', 'Kaffee', 'Sprung', 'Dialog',
    'Umfeld', 'Urlaub', 'Flucht', 'Talent', 'Fusion', 'Kredit', 'Faktum', 'Posten',
    'Betrag', 'Geburt', 'Schnee', 'Lesung', 'Gegend', 'Akteur', 'Formel', 'Gesang',
    'Hektar', 'Verbot', 'Justiz', 'Umfang', 'Profil', 'Jurist', 'Abwehr', 'Gebühr',
    'Pflege', 'Innere', 'Budget', 'Wappen', 'Dritte', 'Silber', 'Symbol', 'Tasche',
    'Leiche', 'Zähler', 'Finger', 'Faktor', 'Unruhe', 'Mandat', 'Ablauf', 'Kaiser',
    'Mieter', 'Kuchen', 'Wurzel', 'Single', 'Effekt', 'Führer', 'Bistum', 'Christ',
    'Wandel', 'Rekord', 'Gipfel', 'Etappe', 'Flügel', 'Frucht', 'Ehrung', 'Einzug',
    'Vision', 'Kammer', 'Athlet', 'Status', 'Obmann', 'Denken', 'Metall', 'Zufall',
    'Schalk', 'Flamme', 'Platte', 'Bronze', 'Spital', 'Studio', 'Ausmaß', 'Schild',
    'Regime', 'Streik', 'Teufel', 'Zweite', 'Tennis', 'Können', 'Spruch', 'Gehalt',
    'Kicker', 'Affäre', 'Reiter', 'Chemie', 'Design', 'Finanz', 'Ticket', 'Option',
    'Strich', 'Tunnel', 'Ferien', 'Abitur', 'Impuls', 'Messer', 'Käufer',
    'Plakat', 'Nutzer', 'Muster', 'Junior', 'Strand', 'Erhalt', 'Absage', 'Rebell',
    'Genuss', 'Einzel', 'Ersatz', 'Mythos', 'Glocke', 'Record', 'Planet', 'Rezept',
    'Online', 'Fabrik', 'Ahnung', 'Nutzen', 'Doppel', 'Aktive', 'Wirken', 'Grafik',
    'Ertrag', 'Terror', 'Abgabe', 'Schatz', 'Kasten', 'Stille', 'Export', 'Kostüm',
    'Tagung', 'Mörder', 'Leiden', 'Zusage', 'Lernen', 'Mittag', 'Flagge', 'Ringen',
    'Akzent', 'Sperre', 'Fremde', 'Tatort', 'Physik', 'Abfall', 'Oberst', 'Winkel',
    'Vortag', 'Wohnen', 'Trikot', 'Schock', 'Geduld', 'Gehirn', 'Rätsel', 'Gemüse',
    'Abgang', 'Rakete', 'Aufruf', 'Belang', 'Visier', 'Master', 'Sparte', 'Pastor',
    'Radweg', 'Anlauf', 'Ostern', 'Rektor', 'Solist', 'Kranke', 'Format', 'Befehl',
    'Betrug', 'Epoche', 'Winzer', 'Lizenz', 'Pleite', 'Review', 'Graben',
    'Trauer', 'Treppe', 'Unsinn', 'Hunger', 'Gattin', 'Auszug', 'Agenda', 'Tempel',
    'Anreiz', 'Appell', 'Redner', 'Weiche', 'Räuber', 'Konsum', 'Charme', 'Sektor',
    'Läufer', 'Tänzer', 'Weiler', 'Breite', 'Turner', 'Fächer', 'Schein', 'Palast',
    'Devise', 'Prämie', 'Panzer', 'Schlaf', 'Portal', 'Geisel', 'Erwerb', 'Speise',
    'Doktor', 'Rivale', 'Anstoß', 'Hockey', 'Marsch', 'Kabine', 'Marine', 'Defekt',
    'Garage', 'Vorzug', 'Zucker', 'Eichel', 'Diesel', 'Antike', 'Benzin',
    'Reifen', 'Ökonom', 'Taktik', 'Furcht', 'Kneipe', 'Tugend', 'Lenker', 'Advent',
    'Kiefer', 'Koffer', 'Becken', 'Ostsee', 'Beirat', 'Balkon', 'Vierte',
    'Parade', 'Laufen', 'Zugabe', 'Gepäck', 'Brille', 'Stange', 'Flanke', 'Irrtum',
    'Insekt', 'Gitter', 'Dozent', 'Ironie', 'Ziffer', 'Sprint', 'Ritual', 'Gräfin',
    'Fliege', 'Pforte', 'Heirat', 'Doping', 'Flotte', 'Parole', 'Revier', 'Eisbär',
    'Pfarre', 'Palais', 'Poesie', 'Konter', 'Chefin', 'Knoten', 'Fehlen', 'Brauch',
    'Patent', 'Zirkus', 'Kläger', 'Statue', 'Ausweg', 'Vulkan', 'Maurer', 'Slogan',
    'Butter', 'Orange', 'Zusatz', 'Prager', 'Podium', 'Casino', 'Teller', 'Campus',
    'Slalom', 'Trasse', 'Action', 'Umland', 'Bremse', 'Vorort', 'Geruch', 'Stätte',
    'Scherz', 'Scheck', 'Modern', 'Inland', 'Radler', 'Dasein', 'Schach', 'Felsen',
    'Banker', 'Muslim', 'Kochen', 'Mantel', 'Befund', 'Folter', 'Tanzen', 'Kenner',
    'Zettel', 'Rubrik', 'Ladung', 'Anhieb', 'Report', 'Retter', 'Ärztin', 'Krippe',
    'Kumpel', 'Erdgas', 'Gewehr', 'Import', 'Siegel', 'Wirbel', 'Daumen', 'Fünfte',
    'Planer', 'Messen', 'Macher', 'Kirmes', 'Ritter', 'Gehweg', 'Fahren', 'Dusche',
    'Walker', 'Schwan', 'Delikt', 'Traube', 'Diener', 'Bäcker', 'Muskel', 'Sparen',
    'Leader', 'Schrei', 'Zensur', 'Strang', 'Renner', 'Sopran', 'Kokain', 'Bagger',
    'Notruf', 'Stütze', 'Kurier', 'Einbau', 'Gewand', 'Sultan', 'Westen', 'Milieu',
    'Ranger', 'Zyklus', 'Sklave', 'Libero', 'Futter', 'Dichte', 'Heroin', 'Binder',
    'Plenum', 'Schale', 'Barock', 'Moslem', 'Skizze', 'Nische', 'Globus', 'Podest',
    'Hering', 'Utopie', 'Rapper', 'Warner', 'Latein', 'Grippe', 'Turnen', 'Grauen',
    'Frosch', 'Aufzug', 'Orient', 'Kupfer', 'Satire', 'Becher', 'Herzog'];


export let words7de = ['Prozent', 'Million', 'Schmale', 'Artikel', 'Sonntag', 'Samstag', 'Problem', 'Freitag',
    'Familie', 'Polizei', 'Oktober', 'Bereich', 'Projekt', 'Februar', 'Trainer', 'Schüler',
    'Zukunft', 'Einsatz', 'Politik', 'Zeitung', 'Beifall', 'Beitrag', 'Spieler', 'Kollege',
    'Aufgabe', 'Angebot', 'Betrieb', 'Bericht', 'Meinung', 'Telefon', 'Mädchen', 'Begriff',
    'Hinweis', 'Gericht', 'Schritt', 'Gebäude', 'Sprache', 'Tochter', 'Führung', 'Konzert',
    'Vertrag', 'Aussage', 'Theater', 'Wohnung', 'Antwort', 'Fußball', 'Behörde', 'Konzept',
    'Kontakt', 'Strecke', 'Meister', 'Auftrag', 'Verband', 'Schaden', 'Sitzung', 'Bündnis',
    'Leitung', 'Beamter', 'Zentrum', 'Vorjahr', 'Ausgabe', 'Produkt', 'Studium', 'Experte',
    'Versuch', 'Energie', 'Vorwurf', 'Gesicht', 'Angriff', 'Treffen', 'Partner', 'Ansicht',
    'Debatte', 'Patient', 'Sekunde', 'Bahnhof', 'Musiker', 'Rathaus', 'Verlust', 'Bildung',
    'Zeichen', 'Verkehr', 'Technik', 'Ausland', 'Landtag', 'Gedanke', 'Auflage', 'Kommune',
    'Verkauf', 'Einfluß', 'Vortrag', 'Student', 'Bischof', 'Konzern', 'Provinz', 'Vorteil',
    'Version', 'Drittel', 'Einheit', 'Zustand', 'Turnier', 'Treffer', 'Pfarrer', 'Auswahl',
    'Wirkung', 'Ursache', 'Zweifel', 'Ordnung', 'Anfrage', 'Gelände', 'Protest', 'Planung',
    'Manager', 'Kloster', 'Wechsel', 'Entwurf', 'Fenster', 'Umstand', 'Branche', 'Station',
    'General', 'Prinzip', 'Nachbar', 'Spiegel', 'Frieden', 'Infobox', 'Galerie', 'Website',
    'Element', 'Richter', 'Umfrage', 'Nutzung', 'Prüfung', 'Methode', 'Tabelle', 'Viertel',
    'Vorbild', 'Pflanze', 'Haltung', 'Auftakt', 'Vorlage', 'Stadion', 'Verlauf', 'Abstand',
    'Service', 'Theorie', 'Autorin', 'Schrift', 'Quartal', 'Pflicht', 'Werbung',
    'Sendung', 'Landrat', 'Gedicht', 'Dutzend', 'Kapitel', 'Gremium', 'Stürmer', 'Kapitän',
    'Händler', 'Tausend', 'Tourist', 'Ehefrau', 'Analyse', 'Dichter', 'Heilige', 'Favorit',
    'Gewicht', 'Magazin', 'Adresse', 'Staffel', 'Absicht', 'Vorfeld', 'Anleger', 'Anzeige',
    'Militär', 'Klavier', 'Kanzler', 'Zuhörer', 'Sponsor', 'Hundert', 'Bestand', 'Denkmal',
    'Gestalt', 'Respekt', 'Alkohol', 'Aufwand', 'Medizin', 'Vorgang', 'Kapelle', 'Eingang',
    'Fassung', 'Schnitt', 'Defizit', 'Anklage', 'Vorgabe', 'Distanz', 'Agentur', 'Gattung',
    'Anstieg', 'Schmerz', 'Meldung', 'unknown', 'Ausflug', 'Bauwerk', 'Vorfall', 'Getränk',
    'Eintrag', 'Gemälde', 'Abfahrt', 'Königin', 'Malerei', 'Seminar', 'Handeln', 'Tendenz',
    'Gerücht', 'Fleisch', 'Fahrrad', 'Pariser', 'Kapital', 'Gitarre', 'Allianz', 'Ehepaar'];

export let words8de = ['Gemeinde', 'Mitglied', 'Beispiel', 'November', 'Dezember', 'Mittwoch', 'Ergebnis', 'Programm',
    'Dienstag', 'Gespräch', 'Besucher', 'Richtung', 'Leistung', 'Internet', 'Künstler', 'Publikum',
    'Geschäft', 'Deutsche', 'Maßnahme', 'Fahrzeug', 'Institut', 'Fraktion', 'Mehrheit', 'Position',
    'Vorstand', 'Sprecher', 'Auftritt', 'Hoffnung', 'Änderung', 'Abschluß', 'Standort', 'Minister',
    'Haushalt', 'Anspruch', 'Karriere', 'Eindruck', 'Qualität', 'Bewegung', 'Kandidat', 'Stimmung',
    'Republik', 'Freiheit', 'Tatsache', 'Stadtrat', 'Ausschuß', 'Funktion', 'Stiftung', 'Ereignis',
    'Polizist', 'Beratung', 'Konflikt', 'Umgebung', 'Material', 'Anschluß', 'Regelung', 'Eintritt',
    'Struktur', 'Frühjahr', 'Bewohner', 'Argument', 'Training', 'Reaktion', 'Ortsteil', 'Aufnahme',
    'Direktor', 'Wahrheit', 'Kollegin', 'Ausdruck', 'Gründung', 'Investor', 'Ausnahme', 'Maschine',
    'Rechnung', 'Premiere', 'Computer', 'Rückkehr', 'Auskunft', 'Festival', 'Sammlung', 'Verdacht',
    'Flugzeug', 'Kenntnis', 'Variante', 'Aufstieg', 'Wachstum', 'Anschlag', 'Einnahme', 'Vorhaben',
    'Aussicht', 'Anhänger', 'Personal', 'Religion', 'Halbzeit', 'Forscher', 'Spannung', 'Friedhof',
    'Kritiker', 'Stellung', 'Homepage', 'Jahrgang', 'Besitzer', 'Akademie', 'Freundin', 'Ensemble',
    'Realität', 'Spieltag', 'Handlung', 'Autobahn', 'Erhöhung', 'Arbeiter', 'Sportler', 'Jubiläum',
    'Benutzer', 'Resultat', 'Zeitraum', 'Dokument', 'Sängerin', 'Geschenk', 'Abschied', 'Bestehen',
    'Anliegen', 'Herkunft', 'Schlacht', 'Anbieter', 'Schatten', 'Landwirt', 'Medaille', 'Standard',
    'Vorgehen', 'Champion', 'Gewinner', 'Einigung', 'Anwohner', 'Großteil', 'Siedlung', 'Amtszeit',
    'Mischung', 'Existenz', 'Prognose', 'Trennung', 'Erlebnis', 'Gasthaus', 'Webseite', 'Rückgang',
    'Bedenken', 'Berufung', 'Kongress', 'Altstadt', 'Hochzeit', 'Netzwerk', 'Bewerber', 'Einbruch',
    'Nachteil', 'Exemplar', 'Leiterin', 'Einblick', 'Vermögen', 'Kabinett', 'Frühling', 'Hinsicht',
    'Dirigent', 'Schwäche', 'Vielfalt', 'Bemühung', 'Abkommen', 'Kampagne', 'Freizeit', 'Handwerk',
    'Wohnhaus', 'Lehrerin', 'Schulter', 'Phänomen', 'Therapie', 'Offizier', 'Gebrauch',
    'Rundfunk', 'Vielzahl', 'Feiertag', 'Anregung', 'Ursprung', 'Hinblick', 'Substanz', 'Übergang',
    'Torhüter', 'Aktionär', 'Halbjahr', 'Fahrbahn', 'Priester', 'Eingriff', 'Fotograf', 'Straftat',
    'Skulptur', 'Kindheit', 'Kleidung', 'Theologe', 'Division', 'Einstieg', 'Workshop', 'Europäer',
    'Original', 'Endspiel', 'Rhythmus', 'Diplomat', 'Überfall', 'Liberale', 'Sanktion', 'Laufbahn',
    'Dresdner', 'Erhebung', 'Fakultät', 'Verzicht', 'Gegenzug', 'Demokrat', 'Drehbuch', 'Gewässer',
    'Sportart', 'Stärkung', 'Fahrgast', 'Apotheke', 'Kreistag', 'Handball', 'Comeback', 'Kardinal',
    'Häftling', 'Bürgerin', 'Eigentum', 'Nachweis', 'Vorrunde', 'Oberliga'];
